### ISSUE TITLE
Fix pocket.core.DistributedLearningEngine

### ISSUE THREAD

**Issue by DzReal** [DzReal/Pocket#2]
At the moment, all resources (model, optimiser etc) related to learning are initialised prior to spawning subprocesses. But classes `torch.nn.parallel.DistributedDataParallel` and `torch.utils.data.DistributedSampler` can not be instantiated before initialising default process group, which is done within a subprocess.

**Comment by FredericZhang** [comment]
This issue has been resolved in e4939a4edbe8f4a983453ff23c9defca8ac851bb
